language: java

matrix:
    include:
    - name: java8
      jdk: openjdk8
      dist: xenial
    
    - name: java11
      jdk: openjdk11
      dist: bionic

    - name: java13
      jdk: openjdk13
      dist: bionic

script:
    - ./gradlew build