#!/bin/sh

project_path=$1
output_dir=$2
epoch=$3
allchanges=$4

$(cd $project_path && git reset --hard master > /dev/null 2>&1 && git clean -f)
present_sha=$(cd ${project_path} && git log --format="%H" -n 1)
present_date=$(cd ${project_path} && git log --date=iso --format="%aD" -n 1)

# Note I am using gdate here (GNU Date)
past_date=$(gdate -R --date="${present_date} -${epoch} days")
past_sha=$(cd ${project_path} && git log --format="%H" --before="${past_date}" -n 1)


echo "$1, $epoch"
echo "$present_sha, $present_date"
echo "$past_sha, $past_date"

if [ $allchanges -eq 1 ];
then
    ./gradlew experiment2:run --args="--sut=$project_path --present $present_sha --past $past_sha --allchanges --output '$output_dir/$epoch'"
else
    ./gradlew experiment2:run --args="--sut=$project_path --present $present_sha --past $past_sha --output '$output_dir/$epoch'"
fi